# Generated by Django 4.1.6 on 2023-02-09 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('C', 'Cleaning'), ('R', 'Restoration'), ('M', 'Maintenance')], default='C', max_length=1)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.art')),
            ],
        ),
    ]
