# Generated by Django 4.1.6 on 2023-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_maintaining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='maintaining',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='maintaining',
            name='date',
            field=models.DateField(verbose_name='Maintenance Date'),
        ),
        migrations.AddField(
            model_name='art',
            name='frames',
            field=models.ManyToManyField(to='main_app.frame'),
        ),
    ]
